# Generated by Django 3.0.7 on 2020-06-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('deleted_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=80)),
                ('province', models.IntegerField(choices=[(1, 'San Jose'), (2, 'Alajuela'), (3, 'Cartago'), (4, 'Heredia'), (5, 'Guanacaste'), (6, 'Puntarenas'), (7, 'Limon')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='province',
        ),
        migrations.AlterField(
            model_name='busroute',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.District'),
        ),
    ]
