# Generated by Django 3.0.7 on 2020-06-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_district_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
