# Generated by Django 3.0.7 on 2020-07-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_user_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KisaUser',
        ),
    ]
