# Generated by Django 3.0.7 on 2020-06-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200623_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.IntegerField(choices=[(1, 'San Jose'), (2, 'Alajuela'), (3, 'Cartago'), (4, 'Heredia'), (5, 'Guanacaste'), (6, 'Puntarenas'), (7, 'Limon')], default=1),
        ),
    ]
